In [3]:
# Import Numpy Library
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [4]:
# Creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])



In [5]:
print(A)

[[2 3]
 [4 5]]


In [6]:
print(B)

[[6 7]
 [8 9]]


In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 2)

Adding the two matrices

In [9]:
sum = A + B


In [10]:
print(sum)

[[ 8 10]
 [12 14]]


In [13]:
# Create two matrices with random values
matrix_1 = np.random.randint(10,size = (3,3))
matrix_2 = np.random.randint(10,size = (3,3))

In [14]:
print(matrix_1)
print(matrix_2)

[[0 8 2]
 [1 7 0]
 [2 6 0]]
[[1 8 5]
 [2 4 3]
 [4 6 9]]


In [15]:
sum = np.add(matrix_1,matrix_2)

In [16]:
print(sum)

[[ 1 16  7]
 [ 3 11  3]
 [ 6 12  9]]


In [19]:
# Create two matrices with random values
matrix_3 = np.random.randint(10,size = (3,3))
matrix_4 = np.random.randint(10,size = (3,4))

In [20]:
sum2 = np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

Matrix Substraction

In [ ]:
# Creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])


In [22]:
print(A)

[[2 3]
 [4 5]]


In [23]:
print(B)

[[6 7]
 [8 9]]


In [21]:
defference = A -B

In [24]:
print(defference)

[[-4 -4]
 [-4 -4]]


In [25]:
diff = np.subtract(A,B)

In [26]:
print(diff)

[[-4 -4]
 [-4 -4]]


In [27]:
matrix_1 = np.random.randint(10,size = (3,3))
matrix_2 = np.random.randint(10,size = (3,3))

In [28]:
print(matrix_1)

[[4 4 1]
 [7 6 4]
 [2 3 4]]


In [29]:
print(matrix_2)

[[2 9 1]
 [6 4 6]
 [2 2 2]]


In [30]:
diff = np.subtract(matrix_1,matrix_2)

In [31]:
print(diff)

[[ 2 -5  0]
 [ 1  2 -2]
 [ 0  1  2]]


**Multiplying a matrix by scalar**

In [32]:
x = 5
y = np.random.randint(10,size=(4,4))

In [33]:
print(y)

[[0 3 0 2]
 [8 2 8 6]
 [5 6 1 0]
 [8 4 1 5]]


In [34]:
product = np.multiply(x,y)

In [35]:
print(product)

[[ 0 15  0 10]
 [40 10 40 30]
 [25 30  5  0]
 [40 20  5 25]]


**Multiplying 2 Matrices**

In [36]:
# Create two matrices with random values
matrix_3 = np.random.randint(10,size = (3,3))
matrix_4 = np.random.randint(10,size = (3,4))

In [37]:
print(matrix_3)

[[5 4 8]
 [7 0 6]
 [1 3 2]]


In [38]:
print(matrix_4)

[[6 8 1 8]
 [2 4 9 9]
 [0 1 9 1]]


In [40]:
product = np.dot(matrix_3,matrix_4)

In [41]:
print(product)

[[ 38  64 113  84]
 [ 42  62  61  62]
 [ 12  22  46  37]]


In [42]:
print(product.shape)

(3, 4)


In [43]:
# Create two matrices with random values
matrix_3 = np.random.randint(10,size = (3,3))
matrix_4 = np.random.randint(10,size = (4,4))

In [44]:
product = np.dot(matrix_3,matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise Matrices Multiplication**

In [45]:
# Create two matrices with random values
matrix_3 = np.random.randint(10,size = (3,3))
matrix_4 = np.random.randint(10,size = (3,3))

In [46]:
print(matrix_3)

[[1 2 5]
 [3 7 6]
 [1 1 5]]


In [47]:
print(matrix_4)

[[2 3 5]
 [9 8 3]
 [3 8 2]]


In [48]:
product = np.multiply(matrix_3,matrix_4)

In [49]:
print(product)

[[ 2  6 25]
 [27 56 18]
 [ 3  8 10]]
