In [4]:
import numpy as np

Creating a Matrix using numpy

In [7]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [8]:
matrix_1.shape  # gives shape of matrix 2*2  - > row * column

(2, 2)

In [11]:
matrix_2 = np.array([[45,65,78],[12,43,90],[34,76,21]])
print(matrix_2)

[[45 65 78]
 [12 43 90]
 [34 76 21]]


In [12]:
print(matrix_2.shape)

(3, 3)


Creating Matrix with Random Values

In [13]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.45474909 0.61029837 0.36271347]
 [0.18751736 0.22657211 0.49961973]
 [0.7862666  0.10275221 0.52048678]]


In [16]:
# Creating matrix with random integers
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

[[58 83 70 42 93]
 [19 51 63 48 29]
 [10 96 23 19 73]
 [57 96 84 65 50]]


Matrix with all the values as 1

In [17]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
matrix_3 = np.ones((2,3),dtype = int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [19]:
matrix_3 = np.ones((10,10),dtype = int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null mMatrix or Zero matrix

In [20]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [22]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Transpose of a Matrix

In [25]:
# Matrix with random integer values
a = np.random.randint(100,size=(4,5))
print(a)

[[24  6 86 77 34]
 [44 27 54 59 30]
 [46 11 78 71 84]
 [72 35 22 99  5]]


In [26]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[24 44 46 72]
 [ 6 27 11 35]
 [86 54 78 22]
 [77 59 71 99]
 [34 30 84  5]]
