NumPy- Numeriacl Python


In [2]:
import numpy as np


List vs Numpy - TimeTaken

In [3]:
from time import process_time

Time taken by a list

In [8]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+1 for i in range(10000)]
end_time= process_time()
print(end_time-start_time)

0.0015315300000002807


By Using NumPy array

In [9]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time  - start_time)

0.00120788400000027


Numpy Array

In [10]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [13]:
# create a 1 dim array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [14]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape


[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [16]:
c = np.array([(1,2,3,4,),(5,6,7,8,)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [18]:
c.shape


(2, 4)

Initial placeholders in numpy arrays

In [20]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# array of a perticular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# create a numpy array with randam values
b = np.random.random((3,4))
print(b)

[[0.60129897 0.27141468 0.58424063 0.71728196]
 [0.87293038 0.87260438 0.34907128 0.12948727]
 [0.21967612 0.8895568  0.81270543 0.66038512]]


In [33]:
# random integer value with a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[87 11 85 11 48]
 [38 85 60 51 33]
 [19 90 73 85 11]]


In [36]:
# array of evenly spaced value --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [41]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [42]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [43]:
# convert a tuple to a numpy array
t1 = (10,20,30,40,50)
t1 = np.asarray(t1)
print(t1)
type(t1)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [44]:
c = np.random.randint(10,90,(5,5))
print(c)

[[23 65 62 53 78]
 [76 85 47 21 20]
 [11 12 53 60 12]
 [14 33 32 55 25]
 [46 55 87 28 17]]


In [45]:
# array dimension
print(c.shape)

(5, 5)


In [46]:
# number of dimensions
print(c.ndim)

2


In [47]:
# number of elements in an array
print(c.size)

25


In [48]:
# checking the data type of the values in the array
print(c.dtype)

int64


Methematical operations on a np array

In [49]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[9 7 5]
 [3 2 3]
 [4 4 9]]
[[19 14 10]
 [10 15 18]
 [18 11 16]]


In [56]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[28 21 15]
 [13 17 21]
 [22 15 25]]
[[-10  -7  -5]
 [ -7 -13 -15]
 [-14  -7  -7]]
[[171  98  50]
 [ 30  30  54]
 [ 72  44 144]]
[[0.47368421 0.5        0.5       ]
 [0.3        0.13333333 0.16666667]
 [0.22222222 0.36363636 0.5625    ]]


In [58]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[11 19 17]
 [13 16 27]
 [13 19 22]]
[[ -9 -11  -9]
 [ -9 -16  -9]
 [-11 -19 -10]]
[[ 10  60  52]
 [ 22   0 162]
 [ 12   0  96]]
[[0.1        0.26666667 0.30769231]
 [0.18181818 0.         0.5       ]
 [0.08333333 0.         0.375     ]]


Array Manipulation

In [60]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 4 9]
 [7 1 6]]
(2, 3)


In [61]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 7]
 [4 1]
 [9 6]]
(3, 2)


In [62]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 6 0]
 [6 4 4]]
(2, 3)


In [64]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 6]
 [6 4]
 [0 4]]
(3, 2)


In [65]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 6 5]
 [8 2 7]]
(2, 3)


In [68]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 6]
 [5 8]
 [2 7]]
(3, 2)
